# Generated by Django 2.0.3 on 2018-04-04 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Board',
        ),
    ]
